### ISSUE TITLE
Duplicate #post_data overrides student method 

### ISSUE THREAD

**Issue by KristenLeach** [learn-co-students/diy-json-serializer-ruby-v-000#105]
In this readme, we are asked to create a method #body in the post controller that serializes the post data, and then later asked to change the name to #post_data. However, there is a method #post_data included in the original repo that is different, and is overriding the results of the student made method. 
Student method from readme: 
`def post_data
    post = Post.find(params[:id])
    render json: PostSerializer.serialize(post)
  end
`
included in repo: 
`def post_data
    post = Post.find(params[:id])
    render plain: post.description
  end`

When the readme says the more link should be returning a JSON object, and continues to change the ajax request to extract only the description, my browser was not showing a JSON object as the included method was already retrieving only the post.description for the get request.

**Comment by jennianelson** [comment]
Thank you for posting this!  I was going crazy trying to figure out what I was doing wrong.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
