### ISSUE TITLE
To get this working in the browser, I had to add 'return false;' to the lesson code

### ISSUE THREAD

**Issue by scirocco21** [learn-co-students/diy-json-serializer-ruby-v-000#131]
In 'show.html.erb', I needed to add `return false;` after setting the link id and closing the inner function and query with `$(".js-next").attr("data-id", data["id"]);
});`;

The 'next' button wouldn't work properly otherwise. Hopefully this will save someone else some time!

**Comment by nhinhdao** [comment]
How can you come up with the solution @scirocco21 ? what is your guide on how to get that **return false**? I noticed the same problem but I don't know what question to google to find out the answer. Thanks

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
