### ISSUE TITLE
Spec issue solution

### ISSUE THREAD

**Issue by Rygel-XVI** [learn-co-students/diy-json-serializer-ruby-v-000#147]
Navigation:
In the form partial it does not create an author or associate one on creation resulting in errors.

To resolve that in the browser adding a safe navigation to the html fixes that problem but not the tests. To   resolve the issue in the tests remove any references to name or author to pass the tests.

<div class="authorName"><%= @post&.author&.name %></div>

Form:
The targeting labels need to be changed in the spec to post_title and post_description from title and description.

For the last test the routes need to be modified to include :update and the student can change the code of the button to be dynamic to pass the tests or the tests can be less specific/dynamic to finally see green.

**Comment by zlehmann** [comment]
Alternatively you can create an Author:
`    @author = Author.create(name: "Some writer guy", hometown: "NYC")
    @post = Post.create(title: "My Post", description: "My post desc", author_id: 1)`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
