### ISSUE TITLE
post_spec.rb attempts to create a Post with un unknown field

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-students/diy-json-serializer-ruby-v-000#152]
The Post model does not have  a 'name' column.
It does have an 'author_id' though

post_spec.rb currently:

describe 'navigate' do
  before do
    @post = Post.create(title: "My Post", description: "My post desc", name: "Steven")
  end

suggested update: 

describe 'navigate' do
  before do
    @post = Post.create(title: "My Post", description: "My post desc", author_id: 1)
  end

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
