### ISSUE TITLE
Javascript example doesn't work

### ISSUE THREAD

**Issue by nothingisfunny** [learn-co-students/diy-json-serializer-ruby-v-000#16]
It seems like this [line](https://github.com/learn-co-students/diy-json-serializer-ruby-v-000/blame/master/README.md#L265):

```javascript
// Replace text of body-id div
$("#body-" + id).html(data["description"]);
```

should be 

```javascript
$("#body-" + id).html(JSON.parse(data)["description"]);
```

**Comment by gj** [comment]
Fixed by using `$.getJSON` instead of `$.get`. Thanks @nothingisfunny !
