### ISSUE TITLE
post_spec.rb calls "Submit Post"

### ISSUE THREAD

**Issue by AReid987** [learn-co-students/diy-json-serializer-ruby-v-000#189]
Starting with line 24 in post_spec.rb the capybara test calls `click_on "Submit Post` 
My suggestion is to change to `click_on "Create Post"` 

then after filling in "title" and "description" the Post show view attempts to render a `post.author.name`, however the form does not currently allow for creating a Post/Author association.
My suggestion is to add an Author field to the _form partial

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
