### ISSUE TITLE
post_spec.rb issue with form tests

### ISSUE THREAD

**Issue by jouissances** [learn-co-students/diy-json-serializer-ruby-v-000#231]
On top of the issues opened by other students, there is a missing :update action in the routes.rb file. This is needed to pass the form test, specifically the edit-and-update test.

Additionally, I also had to change the form's new-and-create test from this:
```
    fill_in 'title', with: "My post title"
    fill_in 'description', with: "My post description"
```
to
```
    fill_in 'post[title]', with: "My post title"
    fill_in 'post[description]', with: "My post description"
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
