### ISSUE TITLE
The tests included in this lab do not relate to what is worked on

### ISSUE THREAD

**Issue by mseaman6** [learn-co-students/diy-json-serializer-ruby-v-000#254]
This would be fine if they were already passing, but they are not. Additionally, you have to make a lot of changes to either the specs or the app to get them to pass (as can be seen by the issues already submitted), since the tests and the existing code do not seem to correspond to each other (i.e. as it exists there are posts and associated authors, but the tests do not deal with authors, and have an additional "name" field for the post, etc.).

Especially since this is a code-along, this could be fixed by simply removing the tests (and would be a lot less frustrating to the students).

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
