### ISSUE TITLE
How to pass this lab

### ISSUE THREAD

**Issue by vibraniumforge** [learn-co-students/diy-json-serializer-ruby-v-000#290]
1. Change spec/features/post_spec.rb line 5 from 

' @post = Post.create(title: "My Post", description: "My post desc", name: "Steven")'
to 
 '@post = Post.create(title: "My Post", description: "My post desc")'

This fixes the ' ActiveRecord::UnknownAttributeError:
       unknown attribute 'name' for Post.'

It will pass the first 3 tests.

2. Comment out line 15 in spec/models/author_spec.rb
This will pass the one pending test with yellow text.

3. Change spec/features/post_spec.rb 
lines 27-31 to:

 fill_in 'post[title]', with: "My post title"
 fill_in 'post[description]', with: "My post description"

    click_on "Create Post"
	
This fixes 'Unable to find field "title"' error on test 4
This was suggested by user jouissances a few posts ago.
Also by AReid987 for the "Create Post".

4. Add "resources :posts" to config/routes.rb. This should pass test 5.

**Comment by Madeline-Stark** [comment]
This was very helpful, thanks! I'd also like to add I needed to remove all lines referencing author and name in my posts/show form in order to pass the tests

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
