### ISSUE TITLE
Had to run 'gem install bundler' + 'bundle install' to execute tests 

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-students/diy-json-serializer-ruby-v-000#343]
error message upon learn command:
"/Users/atxrenegade/.rvm/rubies/ruby-2.3.3/lib/ruby/site_ruby/2.3.0/rubygems.rb:289:in `find_sp
ec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException
)"

**Comment by wendisha** [comment]
I got the same error when trying to run the tests and a shorter version (`You must use Bundler 2 or greater with this lockfile.`) when trying to seed db. Got resolved after upgrating bundler to v2 with: `**bundle update --bundler**`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
