### ISSUE TITLE
gem depreciation that may break app...'"HEADS UP! i18n 1.1 changed fallbacks to exclude default locale. But that may break your application.'

### ISSUE THREAD

**Issue by atxrenegade** [learn-co-students/diy-json-serializer-ruby-v-000#344]
Post-install message from i18n:
Depreciation warning post bundle install:
"HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x."

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
